config/routes.rb
Rails.application.routes.draw do

  root :to => redirect('/words')
  resources :words

end

app/models/word.rb
class Word < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/b_contoller.rb
class bController < ActionController::Base
  def b
    # put any code here that you need 
    # (although for a static view you probably won't have any)
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show]
  
  # :edit, :update, :destroy removed for this assessment

  # GET /words
  # GET /words.json
  def index
    @words = Word.all
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  
  
  
  # Removed for the purposes of this assessment
  
  # GET /words/new
  #def new
    #@word = Word.new
  #end

  # GET /words/1/edit
  #def edit
  #end

  # POST /words
  # POST /words.json
  #def create
    #@word = Word.new(word_params)

    #respond_to do |format|
      #if @word.save
        #format.html { redirect_to @word, notice: 'Word was successfully created.' }
        #format.json { render :show, status: :created, location: @word }
      #else
        #format.html { render :new }
        #format.json { render json: @word.errors, status: :unprocessable_entity }
      #end
    #end
  #end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  #def update
    #respond_to do |format|
      #if @word.update(word_params)
        #format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        #format.json { render :show, status: :ok, location: @word }
      #else
        #format.html { render :edit }
        #format.json { render json: @word.errors, status: :unprocessable_entity }
      #end
    #end
  #end

  # DELETE /words/1
  # DELETE /words/1.json
  #def destroy
   # @word.destroy
    #respond_to do |format|
     # format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      #format.json { head :no_content }
    #end
  #end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.require(:word).permit(:word, :wordtype, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dictionary</title>
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">The Word Dictionary</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/ideas">Words</a></li>
      </ul>
    </div>
  </div>
</nav>
  
  <div class="container">
  <%= yield %>
  </div>

  <footer>
  <div class="container">
  </div>
</footer>
<script src="//railsgirls.com/assets/bootstrap.js"></script>

</body>
</html>

app/views/words/_form.html.erb
<%= form_for(@word) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% @word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %><br>
    <%= f.text_field :word %>
  </div>
  <div class="field">
    <%= f.label :wordtype %><br>
    <%= f.text_field :wordtype %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%= render 'form' %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

<h1>Listing Words</h1>

<table>
  <thead>
    <tr>
      <th>Word</th>
      <th>Wordtype</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= word.word %></td>
        <td><%= word.wordtype %></td>
        <td><%= word.description %></td>
        <%# This code is removed to prevent editing of words>       
        <%# <td><%= link_to 'Show', word %></td>
        <%#<td><%= link_to 'Edit', edit_word_path(word) %></td>
        <%#<td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Word', new_word_path %>

app/views/words/new.html.erb
<h1>New Word</h1>

<%= render 'form' %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
  <%= @word.word %>
</p>

<p>
  <strong>Wordtype:</strong>
  <%= @word.wordtype %>
</p>

<p>
  <strong>Description:</strong>
  <%= @word.description %>
</p>

<%= link_to 'Edit', edit_word_path(@word) %> |
<%= link_to 'Back', words_path %>